### POST request to example server
POST http://localhost:8080/api/drone-telemetry
Content-Type: application/json

{
  "droneId": "RECON-GAZA-2025-003",
  "altitude": 55180.27,
  "speed": 393.83,
  "battery": 99.88,
  "location": {
    "latitude": 31.5022,
    "longitude": 34.4668
  },
  "status": "ON MISSION",
  "timestamp": "2025-07-21T02:19:57.345950+00:00"
}
###